window.onload = function() {
  document.getElementById("ch2").onclick = function() {
    document.getElementById("rr").innerHTML="From Theory to Practice in Teaching Music to Children<br><br>This chapter is all about how to apply different theories to teaching children music. There are many theories of how children develop and learn, looking at different ages and how that correlates with how children interpret and understand music. Specifically, this book emphasizes constructivist learning environments, where the children are able to explore and learn for themselves. At different stages, children are able to discover different aspects of music and have fun while learning. I think this information is very helpful as a teacher, so you can come into a classroom with a general idea of how to engage students depending on their age. Children value having fun and need to be constantly engaged and exploring to develop a love for music. There are many different theories that apply themselves in different ways, and it is helpful as a teacher to have many different ideas of how to teach students to create variation and accommodate different learning styles."
  }
  document.getElementById("ch3").onclick = function() {
    document.getElementById("rr").innerHTML="Methods of Teaching Music to Children<br><br>This chapter goes over three main teaching methods, Dalcroze, Kodaly, and Orff. Dalcroze strongly emphasizes eurhythmics, solfege, and improvisation. It is a very musically centered approach rather than the technically centered approach that is present in many school systems today. I like this approach because I feel like I know too many who have learned instruments well mechanically but have huge gaps in musical understanding. The only limit in this teaching style would be the teacher’s own creativity and energy in order to maintain a fun and engaging atmosphere for students.<br>The Kodaly method is similar to the Dalcroze method in emphasizing musicianship over mechanical learning. Kodaly emphasizes inner hearing and literacy in a way that music is embodied within the student, and the students can understand what they are singing and hearing. There is much less emphasis on improvisation compared to musical literacy. The Orff method emphasizes stages of learning for children. The stages are imitation, exploration, literacy, and improvisation. I like the structure of this method, and it makes it easier to create a larger lesson plan. However, I think it is hard to adapt to a classroom especially when there are students at many different stages of understanding. I would love to try these methods in a childhood classroom setting, because I want to find ways that children can explore and find a passion for music. I also would love to see firsthand how children can be creative and find ways to teach themselves music."
  }
  document.getElementById("ch4").onclick = function() {
    document.getElementById("rr").innerHTML="The Singing Child<br><br>From this chapter, the most important thing I noted was the importance of being creative in finding ways to help children learn music by building off their natural talents. Children love singing and sing naturally, but their range is difficult to manage. They have a large range, but they can only sing accurately well within a small interval. This interval increases over time as the child grows. As a teacher, I found that it is important to keep children engaged by using fun songs that they will enjoy. For example, using fun techniques like the “marionette” to teach PSP, picking good songs for their musical taste and ability, and implementing rounds to introduce separate, individual parts. There are also ways I can subtly push toward more advanced musical topics, such as playing a chord progression with a simple melody and mapping out melodies to develop pitch accuracy. Overall, I think I need to work on gaining experience and confidence in my creative abilities to maintain an entertaining yet worthwhile learning experience."
  }
  document.getElementById("ch5").onclick = function() {
    document.getElementById("rr").innerHTML="Pitch and the Child<br><br>As the child grows, they develop newer and deeper understandings of melody. At an early age, children learn songs and are able to recognize and differentiate different melodies. Soon, they begin to understand concepts of high and low pitch. As a teacher, it can be helpful to use physical or visual cues to demonstrate pitch range. For example, moving the body up and down in accordance with high and low pitches, or using keyboard instruments to visually represent pitch order. After children begin to recognize pitches, they can start grouping pitches together that are closer/farther apart. Eventually, around middle-late elementary, children develop concepts of tonality, pitch centers, and musical phrasing. Children often grasp these concepts in some form naturally by listening to music around them. It is important for the teacher to help guide the students in consciously engaging with music. While music is a very natural skill, the teacher must use many different methods to move a child from musical sensitivity and feeling toward a conscious and skillful understanding of music."
  }
  document.getElementById("ch6").onclick = function() {
    document.getElementById("rr").innerHTML="The Moving Child<br><br>Children love to move naturally, and it is our job as music teachers to shape these natural inclinations into an understanding of rhythm, melody, and other musical sensitivities. Movement is very helpful in helping a child hard musical concepts, so that they are able to become more musical instead of simply learning musical concepts. Children are able to further gain command of movement in musical concepts as they grow in motor and muscular development. Using fun songs with lyrics that correspond to movement (eurhythmics), creative movement, and dancing are fun ways to keep children engaged in a meaningful way. I think my favorite activities are eurhythmics and creative movement because they are really fun and low-stakes methods for children to engage in musical movement. Dancing can be fun, but it runs the risk of creating large differences between those who are able to quickly understand and remember instructions and those who are not. It could lead to a larger focus on learning specific movements rather than understanding musical concepts through movement. It is also helpful to keep in mind that movement can be useful to represent many musical concepts other than rhythm."
  }
  document.getElementById("ch7").onclick = function() {
    document.getElementById("rr").innerHTML="Rhythm and the Child<br><br>Rhythm, like movement, is everywhere in childhood. As long as a child receives the proper musical guidance, concepts of rhythm will develop as the child develops. The textbook recommends that children begin with concepts of fast/slow, long/short; and eventually leading to reading rhythmic notation by the end of their elementary education. A very useful tool for teaching rhythm, beside movement, is speech. Orff and Kodaly use a lot of words and syllables to build the foundation for rhythm, and it is important to be intentional with which syllables are being used for teaching rhythm. When teaching rhythm, I think it is very important to stay within a context of a basic pulse and meter. These concepts can be established through different movements (e.g. using a specific movement to accent the downbeat when teaching pulse) and conducting. Even as children continue to learn more complex rhythms, syncopation, or polyrhythms; it is crucial to teach these concepts within a context of a normal rhythm.<br>I also enjoy how the textbook so far has provided many step by step approaches, so that children and teachers are able to see different levels on understanding in order to create a more productive learning environment."
  }
  document.getElementById("ch8").onclick = function() {
    document.getElementById("rr").innerHTML="The Playing Child<br><br>Children love playing, and they love playing with musical instruments. As a child develops physically, their ability to play music grows in correlation. Many techniques, such as those developed by Orff and Suzuki, guide a children’s musical education with their growth over time. These approaches are great step-by-step approaches to ingrain deep musical understanding into a child, and I especially like how Suzuki emphasizes delaying music reading until the child has a firm grasp on musical concepts. The only problem is most children to not have access to a step by step music program that follows them from a very young age. So, it is important as a music educator to provide proper musical experiences that match the child’s stage of growth. Body percussion and non-pitched percussion instruments are great ways to introduce playing musical instruments. In a classroom setting, the Orff methods uses many instruments, using many melodic instruments accompanied by many non-pitched instruments. Orff’s technique of using a mallet instrument with removable keys is very helpful in making instrumental playing simpler for children. There are many other pitched instruments that students can easily learn to play, such as the recorder, autoharp, guitar, and keyboards. For many children, instrumental music is the epitome and realization of many abstract musical concepts. However, it is always important to be careful to make sure children have a strong sense of musical understanding before a mechanical understanding of playing an instrument."
  }
  document.getElementById("ch14").onclick = function() {
    document.getElementById("rr").innerHTML="Curriculum Design<br><br>As a teacher, it is important to organized with a lesson plan before every lesson. Having objectives and goals to meet can help students tangibly learn concepts and deliberately practice their musical skills. However, teachers also have to be flexible and dynamic in order to shape a personal experience for each student. Curriculum can change depending on student’s individual needs, access to resources, and cultural backgrounds. There are many types of curricula, ranging from less formal to more formal, that all take into account Local, State, and National standards of music education. A good teacher should be able to use these guidelines to create a comprehensive lesson plan for the year, using each point to create specific goals to work on throughout the year. As a teacher, I think I need to work on being able to break down general topics into intentional specific topics that students and more easily perceive and learn."
  }
  document.getElementById("ch15").onclick = function() {
    document.getElementById("rr").innerHTML="Assessment and Evaluation<br><br>Assessment is an essential system of accountability for the classroom. It allows for the teacher to understand how well the student is receiving material, and helps the student assess their own progress in the classroom. Especially in music education, assessment runs the risk of being too subjective, so teachers should attempt to create standards that are tangible. Like curriculum, there is a range of formal and informal assessment constantly in the classroom. Most of the time, there is informal assessment by the teacher. Students should also be able to assess their own progress, whether through informal self-evaluation, portfolios, or peer assessment. This book also defines a difference between testing, measurement, and assessment. I don’t think this is necessary, and the book creates these divisions in an unclear way, mostly based on how much one uses numbers to assess students."
  }
  document.getElementById("ch16").onclick = function() {
    document.getElementById("rr").innerHTML="Music in an Integrated Curriculum<br><br>This chapter focuses a lot on integrating music with art and other subjects in school. I love the concept of arts integration because it removes the notion that music is a just separate hobby or fun but unnecessary extracurricular. The arts can be used as an enjoyable and enriching way to understand universal concepts of repetition, themes, emotional expression, etc. Because music is an integral part of human culture and experience, there are many ways to study society and culture from a musical viewpoint. Overall, an integrated learning from many viewpoints can enhance musical and overall understanding and education."
  }
}
